/*
 * This file is generated by jOOQ.
 */
package com.kyc.game.dao.tables.interfaces;


import java.time.LocalDateTime;


/**
 * 配置
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IConfig {

    /**
     * Setter for <code>game-strategy.config.id</code>. 主键
     */
    public void setId(Integer value);

    /**
     * Getter for <code>game-strategy.config.id</code>. 主键
     */
    public Integer getId();

    /**
     * Setter for <code>game-strategy.config.key</code>. 配置项
     */
    public void setKey(String value);

    /**
     * Getter for <code>game-strategy.config.key</code>. 配置项
     */
    public String getKey();

    /**
     * Setter for <code>game-strategy.config.value</code>. 值
     */
    public void setValue(String value);

    /**
     * Getter for <code>game-strategy.config.value</code>. 值
     */
    public String getValue();

    /**
     * Setter for <code>game-strategy.config.description</code>. 描述
     */
    public void setDescription(String value);

    /**
     * Getter for <code>game-strategy.config.description</code>. 描述
     */
    public String getDescription();

    /**
     * Setter for <code>game-strategy.config.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value);

    /**
     * Getter for <code>game-strategy.config.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime();

    /**
     * Setter for <code>game-strategy.config.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value);

    /**
     * Getter for <code>game-strategy.config.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IConfig
     */
    public void from(IConfig from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IConfig
     */
    public <E extends IConfig> E into(E into);
}
