/*
 * This file is generated by jOOQ.
 */
package com.kyc.game.dao.tables.interfaces;


import java.time.LocalDateTime;


/**
 * 角色
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface IRole {

    /**
     * Setter for <code>game-strategy.role.id</code>. 角色id
     */
    public void setId(Integer value);

    /**
     * Getter for <code>game-strategy.role.id</code>. 角色id
     */
    public Integer getId();

    /**
     * Setter for <code>game-strategy.role.name</code>. 角色名称
     */
    public void setName(String value);

    /**
     * Getter for <code>game-strategy.role.name</code>. 角色名称
     */
    public String getName();

    /**
     * Setter for <code>game-strategy.role.auth</code>. 角色权限
     */
    public void setAuth(String value);

    /**
     * Getter for <code>game-strategy.role.auth</code>. 角色权限
     */
    public String getAuth();

    /**
     * Setter for <code>game-strategy.role.create_time</code>. 创建时间
     */
    public void setCreateTime(LocalDateTime value);

    /**
     * Getter for <code>game-strategy.role.create_time</code>. 创建时间
     */
    public LocalDateTime getCreateTime();

    /**
     * Setter for <code>game-strategy.role.update_time</code>. 更新时间
     */
    public void setUpdateTime(LocalDateTime value);

    /**
     * Getter for <code>game-strategy.role.update_time</code>. 更新时间
     */
    public LocalDateTime getUpdateTime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common
     * interface IRole
     */
    public void from(IRole from);

    /**
     * Copy data into another generated Record/POJO implementing the common
     * interface IRole
     */
    public <E extends IRole> E into(E into);
}
