/*
 * This file is generated by jOOQ.
 */
package com.kyc.game.dao.tables.daos;


import com.kyc.game.dao.tables.Role;
import com.kyc.game.dao.tables.records.RoleRecord;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * 角色
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class RoleDao extends DAOImpl<RoleRecord, com.kyc.game.dao.tables.pojos.Role, Integer> {

    /**
     * Create a new RoleDao without any configuration
     */
    public RoleDao() {
        super(Role.ROLE, com.kyc.game.dao.tables.pojos.Role.class);
    }

    /**
     * Create a new RoleDao with an attached configuration
     */
    @Autowired
    public RoleDao(Configuration configuration) {
        super(Role.ROLE, com.kyc.game.dao.tables.pojos.Role.class, configuration);
    }

    @Override
    public Integer getId(com.kyc.game.dao.tables.pojos.Role object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.kyc.game.dao.tables.pojos.Role> fetchRangeOfId(Integer lowerInclusive, Integer upperInclusive) {
        return fetchRange(Role.ROLE.ID, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.kyc.game.dao.tables.pojos.Role> fetchById(Integer... values) {
        return fetch(Role.ROLE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.kyc.game.dao.tables.pojos.Role fetchOneById(Integer value) {
        return fetchOne(Role.ROLE.ID, value);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public Optional<com.kyc.game.dao.tables.pojos.Role> fetchOptionalById(Integer value) {
        return fetchOptional(Role.ROLE.ID, value);
    }

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.kyc.game.dao.tables.pojos.Role> fetchRangeOfName(String lowerInclusive, String upperInclusive) {
        return fetchRange(Role.ROLE.NAME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.kyc.game.dao.tables.pojos.Role> fetchByName(String... values) {
        return fetch(Role.ROLE.NAME, values);
    }

    /**
     * Fetch records that have <code>auth BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.kyc.game.dao.tables.pojos.Role> fetchRangeOfAuth(String lowerInclusive, String upperInclusive) {
        return fetchRange(Role.ROLE.AUTH, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>auth IN (values)</code>
     */
    public List<com.kyc.game.dao.tables.pojos.Role> fetchByAuth(String... values) {
        return fetch(Role.ROLE.AUTH, values);
    }

    /**
     * Fetch records that have <code>create_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.kyc.game.dao.tables.pojos.Role> fetchRangeOfCreateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Role.ROLE.CREATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>create_time IN (values)</code>
     */
    public List<com.kyc.game.dao.tables.pojos.Role> fetchByCreateTime(LocalDateTime... values) {
        return fetch(Role.ROLE.CREATE_TIME, values);
    }

    /**
     * Fetch records that have <code>update_time BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    public List<com.kyc.game.dao.tables.pojos.Role> fetchRangeOfUpdateTime(LocalDateTime lowerInclusive, LocalDateTime upperInclusive) {
        return fetchRange(Role.ROLE.UPDATE_TIME, lowerInclusive, upperInclusive);
    }

    /**
     * Fetch records that have <code>update_time IN (values)</code>
     */
    public List<com.kyc.game.dao.tables.pojos.Role> fetchByUpdateTime(LocalDateTime... values) {
        return fetch(Role.ROLE.UPDATE_TIME, values);
    }
}
