server:
  port: 9090

spring:
  application:
    name: game-strategy

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/game-strategy?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=GMT
    username: root
    password: "20150262"
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:/db/master.yml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
    drop-first: false


