server:
  port: 9090

spring:
  profiles:
    active: "database"
  application:
    name: game-strategy

#  cloud:
#    nacos:
#      config:
#        enabled: true
#        server-addr: localhost:8848
#        file-extension: yaml
#
#  config:
#    import: nacos:game-strategy-dev.yaml

  liquibase:
    change-log: classpath:/db/master.yml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: false
    drop-first: false



