databaseChangeLog:
  - changeSet:
      id: 2023080701
      author: kyc
      changes:
        - createTable:
            tableName: config
            remarks: 配置
            columns:
              - column:
                  name: id
                  type: int(11)
                  remarks: 主键
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: key
                  type: varchar(128)
                  remarks: 配置项
              - column:
                  name: value
                  type: varchar(127)
                  remarks: 值
              - column:
                  name: description
                  type: varchar(127)
                  remarks: 描述
              - column:
                  name: create_time
                  type: datetime
                  remarks: 创建时间
                  defaultValueDate: now()
              - column:
                  name: update_time
                  type: datetime
                  remarks: 更新时间
                  defaultValueDate: now()