/*
 * This file is generated by jOOQ.
 */
package com.kyc.game.dao;


import com.kyc.game.dao.tables.Config;
import com.kyc.game.dao.tables.Role;
import com.kyc.game.dao.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameStrategy extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>game-strategy</code>
     */
    public static final GameStrategy GAME_STRATEGY = new GameStrategy();

    /**
     * 配置
     */
    public final Config CONFIG = Config.CONFIG;

    /**
     * 角色
     */
    public final Role ROLE = Role.ROLE;

    /**
     * 用户
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private GameStrategy() {
        super("game-strategy", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Config.CONFIG,
            Role.ROLE,
            User.USER
        );
    }
}
