/*
 * This file is generated by jOOQ.
 */
package com.kyc.game.dao;


import com.kyc.game.dao.tables.User;


/**
 * Convenience access to all tables in game-strategy.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 用户
     */
    public static final User USER = User.USER;
}
