/*
 * This file is generated by jOOQ.
 */
package com.kyc.game.dao;


import com.kyc.game.dao.tables.Config;
import com.kyc.game.dao.tables.Role;
import com.kyc.game.dao.tables.User;


/**
 * Convenience access to all tables in game-strategy.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 配置
     */
    public static final Config CONFIG = Config.CONFIG;

    /**
     * 角色
     */
    public static final Role ROLE = Role.ROLE;

    /**
     * 用户
     */
    public static final User USER = User.USER;
}
