/*
 * This file is generated by jOOQ.
 */
package com.kyc.game.dao.tables;


import com.kyc.game.dao.GameStrategy;
import com.kyc.game.dao.Keys;
import com.kyc.game.dao.tables.records.ConfigRecord;

import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function6;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row6;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 配置
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Config extends TableImpl<ConfigRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>game-strategy.config</code>
     */
    public static final Config CONFIG = new Config();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConfigRecord> getRecordType() {
        return ConfigRecord.class;
    }

    /**
     * The column <code>game-strategy.config.id</code>. 主键
     */
    public final TableField<ConfigRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "主键");

    /**
     * The column <code>game-strategy.config.key</code>. 配置项
     */
    public final TableField<ConfigRecord, String> KEY = createField(DSL.name("key"), SQLDataType.VARCHAR(128), this, "配置项");

    /**
     * The column <code>game-strategy.config.value</code>. 值
     */
    public final TableField<ConfigRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(127), this, "值");

    /**
     * The column <code>game-strategy.config.description</code>. 描述
     */
    public final TableField<ConfigRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(127), this, "描述");

    /**
     * The column <code>game-strategy.config.create_time</code>. 创建时间
     */
    public final TableField<ConfigRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "创建时间");

    /**
     * The column <code>game-strategy.config.update_time</code>. 更新时间
     */
    public final TableField<ConfigRecord, LocalDateTime> UPDATE_TIME = createField(DSL.name("update_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "更新时间");

    private Config(Name alias, Table<ConfigRecord> aliased) {
        this(alias, aliased, null);
    }

    private Config(Name alias, Table<ConfigRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("配置"), TableOptions.table());
    }

    /**
     * Create an aliased <code>game-strategy.config</code> table reference
     */
    public Config(String alias) {
        this(DSL.name(alias), CONFIG);
    }

    /**
     * Create an aliased <code>game-strategy.config</code> table reference
     */
    public Config(Name alias) {
        this(alias, CONFIG);
    }

    /**
     * Create a <code>game-strategy.config</code> table reference
     */
    public Config() {
        this(DSL.name("config"), null);
    }

    public <O extends Record> Config(Table<O> child, ForeignKey<O, ConfigRecord> key) {
        super(child, key, CONFIG);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : GameStrategy.GAME_STRATEGY;
    }

    @Override
    public Identity<ConfigRecord, Integer> getIdentity() {
        return (Identity<ConfigRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<ConfigRecord> getPrimaryKey() {
        return Keys.KEY_CONFIG_PRIMARY;
    }

    @Override
    public Config as(String alias) {
        return new Config(DSL.name(alias), this);
    }

    @Override
    public Config as(Name alias) {
        return new Config(alias, this);
    }

    @Override
    public Config as(Table<?> alias) {
        return new Config(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Config rename(String name) {
        return new Config(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Config rename(Name name) {
        return new Config(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Config rename(Table<?> name) {
        return new Config(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row6 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function6<? super Integer, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function6<? super Integer, ? super String, ? super String, ? super String, ? super LocalDateTime, ? super LocalDateTime, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
