/*
 * This file is generated by jOOQ.
 */
package com.kyc.game.dao.tables.records;


import com.kyc.game.dao.tables.Config;
import com.kyc.game.dao.tables.interfaces.IConfig;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 配置
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ConfigRecord extends UpdatableRecordImpl<ConfigRecord> implements Record6<Integer, String, String, String, LocalDateTime, LocalDateTime>, IConfig {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>game-strategy.config.id</code>. 主键
     */
    @Override
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>game-strategy.config.id</code>. 主键
     */
    @Override
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>game-strategy.config.key</code>. 配置项
     */
    @Override
    public void setKey(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>game-strategy.config.key</code>. 配置项
     */
    @Override
    public String getKey() {
        return (String) get(1);
    }

    /**
     * Setter for <code>game-strategy.config.value</code>. 值
     */
    @Override
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>game-strategy.config.value</code>. 值
     */
    @Override
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>game-strategy.config.description</code>. 描述
     */
    @Override
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>game-strategy.config.description</code>. 描述
     */
    @Override
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>game-strategy.config.create_time</code>. 创建时间
     */
    @Override
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>game-strategy.config.create_time</code>. 创建时间
     */
    @Override
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>game-strategy.config.update_time</code>. 更新时间
     */
    @Override
    public void setUpdateTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>game-strategy.config.update_time</code>. 更新时间
     */
    @Override
    public LocalDateTime getUpdateTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Integer, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Integer, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Config.CONFIG.ID;
    }

    @Override
    public Field<String> field2() {
        return Config.CONFIG.KEY;
    }

    @Override
    public Field<String> field3() {
        return Config.CONFIG.VALUE;
    }

    @Override
    public Field<String> field4() {
        return Config.CONFIG.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return Config.CONFIG.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return Config.CONFIG.UPDATE_TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getKey();
    }

    @Override
    public String component3() {
        return getValue();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component6() {
        return getUpdateTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getKey();
    }

    @Override
    public String value3() {
        return getValue();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value6() {
        return getUpdateTime();
    }

    @Override
    public ConfigRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ConfigRecord value2(String value) {
        setKey(value);
        return this;
    }

    @Override
    public ConfigRecord value3(String value) {
        setValue(value);
        return this;
    }

    @Override
    public ConfigRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public ConfigRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public ConfigRecord value6(LocalDateTime value) {
        setUpdateTime(value);
        return this;
    }

    @Override
    public ConfigRecord values(Integer value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IConfig from) {
        setId(from.getId());
        setKey(from.getKey());
        setValue(from.getValue());
        setDescription(from.getDescription());
        setCreateTime(from.getCreateTime());
        setUpdateTime(from.getUpdateTime());
    }

    @Override
    public <E extends IConfig> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConfigRecord
     */
    public ConfigRecord() {
        super(Config.CONFIG);
    }

    /**
     * Create a detached, initialised ConfigRecord
     */
    public ConfigRecord(Integer id, String key, String value, String description, LocalDateTime createTime, LocalDateTime updateTime) {
        super(Config.CONFIG);

        setId(id);
        setKey(key);
        setValue(value);
        setDescription(description);
        setCreateTime(createTime);
        setUpdateTime(updateTime);
    }

    /**
     * Create a detached, initialised ConfigRecord
     */
    public ConfigRecord(com.kyc.game.dao.tables.pojos.Config value) {
        super(Config.CONFIG);

        if (value != null) {
            setId(value.getId());
            setKey(value.getKey());
            setValue(value.getValue());
            setDescription(value.getDescription());
            setCreateTime(value.getCreateTime());
            setUpdateTime(value.getUpdateTime());
        }
    }
}
