/*
 * This file is generated by jOOQ.
 */
package com.kyc.game.dao.tables.pojos;


import com.kyc.game.dao.tables.interfaces.IConfig;

import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * 配置
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Config implements IConfig, Serializable {

    private Integer id;
    private String key;
    private String value;
    private String description;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;

    public Config() {
    }

    public Config(IConfig value) {
        this.id = value.getId();
        this.key = value.getKey();
        this.value = value.getValue();
        this.description = value.getDescription();
        this.createTime = value.getCreateTime();
        this.updateTime = value.getUpdateTime();
    }

    public Config(
            Integer id,
            String key,
            String value,
            String description,
            LocalDateTime createTime,
            LocalDateTime updateTime
    ) {
        this.id = id;
        this.key = key;
        this.value = value;
        this.description = description;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>game-strategy.config.id</code>. 主键
     */
    @Override
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>game-strategy.config.id</code>. 主键
     */
    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>game-strategy.config.key</code>. 配置项
     */
    @Override
    public String getKey() {
        return this.key;
    }

    /**
     * Setter for <code>game-strategy.config.key</code>. 配置项
     */
    @Override
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Getter for <code>game-strategy.config.value</code>. 值
     */
    @Override
    public String getValue() {
        return this.value;
    }

    /**
     * Setter for <code>game-strategy.config.value</code>. 值
     */
    @Override
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Getter for <code>game-strategy.config.description</code>. 描述
     */
    @Override
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>game-strategy.config.description</code>. 描述
     */
    @Override
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>game-strategy.config.create_time</code>. 创建时间
     */
    @Override
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>game-strategy.config.create_time</code>. 创建时间
     */
    @Override
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>game-strategy.config.update_time</code>. 更新时间
     */
    @Override
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>game-strategy.config.update_time</code>. 更新时间
     */
    @Override
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Config other = (Config) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        } else if (!this.id.equals(other.id))
            return false;
        if (this.key == null) {
            if (other.key != null)
                return false;
        } else if (!this.key.equals(other.key))
            return false;
        if (this.value == null) {
            if (other.value != null)
                return false;
        } else if (!this.value.equals(other.value))
            return false;
        if (this.description == null) {
            if (other.description != null)
                return false;
        } else if (!this.description.equals(other.description))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        } else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        } else if (!this.updateTime.equals(other.updateTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.key == null) ? 0 : this.key.hashCode());
        result = prime * result + ((this.value == null) ? 0 : this.value.hashCode());
        result = prime * result + ((this.description == null) ? 0 : this.description.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Config (");

        sb.append(id);
        sb.append(", ").append(key);
        sb.append(", ").append(value);
        sb.append(", ").append(description);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IConfig from) {
        setId(from.getId());
        setKey(from.getKey());
        setValue(from.getValue());
        setDescription(from.getDescription());
        setCreateTime(from.getCreateTime());
        setUpdateTime(from.getUpdateTime());
    }

    @Override
    public <E extends IConfig> E into(E into) {
        into.from(this);
        return into;
    }
}
