/*
 * This file is generated by jOOQ.
 */
package com.kyc.game.dao.tables.pojos;


import com.kyc.game.dao.tables.interfaces.IRole;

import java.time.LocalDateTime;


/**
 * 角色
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Role implements IRole {

    private Integer id;
    private String name;
    private String auth;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;

    public Role() {}

    public Role(IRole value) {
        this.id = value.getId();
        this.name = value.getName();
        this.auth = value.getAuth();
        this.createTime = value.getCreateTime();
        this.updateTime = value.getUpdateTime();
    }

    public Role(
        Integer id,
        String name,
        String auth,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.name = name;
        this.auth = auth;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>game-strategy.role.id</code>. 角色id
     */
    @Override
    public Integer getId() {
        return this.id;
    }

    /**
     * Setter for <code>game-strategy.role.id</code>. 角色id
     */
    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Getter for <code>game-strategy.role.name</code>. 角色名称
     */
    @Override
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>game-strategy.role.name</code>. 角色名称
     */
    @Override
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>game-strategy.role.auth</code>. 角色权限
     */
    @Override
    public String getAuth() {
        return this.auth;
    }

    /**
     * Setter for <code>game-strategy.role.auth</code>. 角色权限
     */
    @Override
    public void setAuth(String auth) {
        this.auth = auth;
    }

    /**
     * Getter for <code>game-strategy.role.create_time</code>. 创建时间
     */
    @Override
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>game-strategy.role.create_time</code>. 创建时间
     */
    @Override
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>game-strategy.role.update_time</code>. 更新时间
     */
    @Override
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>game-strategy.role.update_time</code>. 更新时间
     */
    @Override
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Role other = (Role) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.auth == null) {
            if (other.auth != null)
                return false;
        }
        else if (!this.auth.equals(other.auth))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.auth == null) ? 0 : this.auth.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Role (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(auth);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IRole from) {
        setId(from.getId());
        setName(from.getName());
        setAuth(from.getAuth());
        setCreateTime(from.getCreateTime());
        setUpdateTime(from.getUpdateTime());
    }

    @Override
    public <E extends IRole> E into(E into) {
        into.from(this);
        return into;
    }
}
