/*
 * This file is generated by jOOQ.
 */
package com.kyc.game.dao.tables.pojos;


import com.kyc.game.dao.tables.interfaces.IUser;

import java.time.LocalDateTime;


/**
 * 用户
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements IUser {

    private Long id;
    private String username;
    private String password;
    private String email;
    private String mobile;
    private Integer role;
    private String avatar;
    private LocalDateTime createTime;
    private LocalDateTime updateTime;

    public User() {}

    public User(IUser value) {
        this.id = value.getId();
        this.username = value.getUsername();
        this.password = value.getPassword();
        this.email = value.getEmail();
        this.mobile = value.getMobile();
        this.role = value.getRole();
        this.avatar = value.getAvatar();
        this.createTime = value.getCreateTime();
        this.updateTime = value.getUpdateTime();
    }

    public User(
        Long id,
        String username,
        String password,
        String email,
        String mobile,
        Integer role,
        String avatar,
        LocalDateTime createTime,
        LocalDateTime updateTime
    ) {
        this.id = id;
        this.username = username;
        this.password = password;
        this.email = email;
        this.mobile = mobile;
        this.role = role;
        this.avatar = avatar;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    /**
     * Getter for <code>game-strategy.user.id</code>. 主键
     */
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>game-strategy.user.id</code>. 主键
     */
    @Override
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>game-strategy.user.username</code>. 用户名
     */
    @Override
    public String getUsername() {
        return this.username;
    }

    /**
     * Setter for <code>game-strategy.user.username</code>. 用户名
     */
    @Override
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for <code>game-strategy.user.password</code>. 密码
     */
    @Override
    public String getPassword() {
        return this.password;
    }

    /**
     * Setter for <code>game-strategy.user.password</code>. 密码
     */
    @Override
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Getter for <code>game-strategy.user.email</code>. 邮箱
     */
    @Override
    public String getEmail() {
        return this.email;
    }

    /**
     * Setter for <code>game-strategy.user.email</code>. 邮箱
     */
    @Override
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Getter for <code>game-strategy.user.mobile</code>. 手机号
     */
    @Override
    public String getMobile() {
        return this.mobile;
    }

    /**
     * Setter for <code>game-strategy.user.mobile</code>. 手机号
     */
    @Override
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * Getter for <code>game-strategy.user.role</code>. 用户角色
     */
    @Override
    public Integer getRole() {
        return this.role;
    }

    /**
     * Setter for <code>game-strategy.user.role</code>. 用户角色
     */
    @Override
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * Getter for <code>game-strategy.user.avatar</code>. 头像地址
     */
    @Override
    public String getAvatar() {
        return this.avatar;
    }

    /**
     * Setter for <code>game-strategy.user.avatar</code>. 头像地址
     */
    @Override
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * Getter for <code>game-strategy.user.create_time</code>. 创建时间
     */
    @Override
    public LocalDateTime getCreateTime() {
        return this.createTime;
    }

    /**
     * Setter for <code>game-strategy.user.create_time</code>. 创建时间
     */
    @Override
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * Getter for <code>game-strategy.user.update_time</code>. 更新时间
     */
    @Override
    public LocalDateTime getUpdateTime() {
        return this.updateTime;
    }

    /**
     * Setter for <code>game-strategy.user.update_time</code>. 更新时间
     */
    @Override
    public void setUpdateTime(LocalDateTime updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final User other = (User) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.username == null) {
            if (other.username != null)
                return false;
        }
        else if (!this.username.equals(other.username))
            return false;
        if (this.password == null) {
            if (other.password != null)
                return false;
        }
        else if (!this.password.equals(other.password))
            return false;
        if (this.email == null) {
            if (other.email != null)
                return false;
        }
        else if (!this.email.equals(other.email))
            return false;
        if (this.mobile == null) {
            if (other.mobile != null)
                return false;
        }
        else if (!this.mobile.equals(other.mobile))
            return false;
        if (this.role == null) {
            if (other.role != null)
                return false;
        }
        else if (!this.role.equals(other.role))
            return false;
        if (this.avatar == null) {
            if (other.avatar != null)
                return false;
        }
        else if (!this.avatar.equals(other.avatar))
            return false;
        if (this.createTime == null) {
            if (other.createTime != null)
                return false;
        }
        else if (!this.createTime.equals(other.createTime))
            return false;
        if (this.updateTime == null) {
            if (other.updateTime != null)
                return false;
        }
        else if (!this.updateTime.equals(other.updateTime))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.username == null) ? 0 : this.username.hashCode());
        result = prime * result + ((this.password == null) ? 0 : this.password.hashCode());
        result = prime * result + ((this.email == null) ? 0 : this.email.hashCode());
        result = prime * result + ((this.mobile == null) ? 0 : this.mobile.hashCode());
        result = prime * result + ((this.role == null) ? 0 : this.role.hashCode());
        result = prime * result + ((this.avatar == null) ? 0 : this.avatar.hashCode());
        result = prime * result + ((this.createTime == null) ? 0 : this.createTime.hashCode());
        result = prime * result + ((this.updateTime == null) ? 0 : this.updateTime.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(username);
        sb.append(", ").append(password);
        sb.append(", ").append(email);
        sb.append(", ").append(mobile);
        sb.append(", ").append(role);
        sb.append(", ").append(avatar);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IUser from) {
        setId(from.getId());
        setUsername(from.getUsername());
        setPassword(from.getPassword());
        setEmail(from.getEmail());
        setMobile(from.getMobile());
        setRole(from.getRole());
        setAvatar(from.getAvatar());
        setCreateTime(from.getCreateTime());
        setUpdateTime(from.getUpdateTime());
    }

    @Override
    public <E extends IUser> E into(E into) {
        into.from(this);
        return into;
    }
}
